In [4]:
import numpy as np
print(np.__version__)   # 会输出numpy版本

1.21.6


In [4]:
# 一维数组
a = np.array([1,2,3,4])
print(a)
print(type(a))   # 打印数据类型
# print(a.min())   # 打印最小值
# print(a.max())   # 打印最大值

# 切片操作
print(a[-1])   # 取最后一个值

print(a[::-1])  # 进行倒叙（把1234变成4321）  ndarray不可以使用reverse
a.sort()  #排序
# print(a)

# ndarray 自己的东西
print(a.shape)  # 打印形状 [4列]


[1 2 3 4]
<class 'numpy.ndarray'>
4
[4 3 2 1]
(4,)


In [5]:
# 二维

b = np.array([[1,2,3,4],[4,6,7,8],[9,10,11,12]])
# print(b)
print('------------------------')
print(a.shape)  # 打印形状
print(b.min(),b.max())  # 打印最大值，最小值
# 索引取值
# print(b[0][0])  #运行结果第一行第一个元素
# print(b[2][3])  #运行结果第三行第四个元素

# 切片
# print(b[1][:]) #[4 6 7 8]
# print(b[:][0]) #[1 2 3 4]
print(b[0:][:-1])  

------------------------


NameError: name 'a' is not defined

In [6]:
#  三维 数组（Arrays）
"""
特点：1.array()把python的类型转换正np的ndarray类型
      2.转换过数组的原始数据不变
函数： 1.最大值 max（）
       2.最小值 min（）
索引和切片：
       1. 通过元素的下标位
       2.通过元素的start：stop
排序： 1.sort
       2.sorted
获取列的值：
     1.[1,1] 返回一个一维数组
    2.[1,np,newaxis,1] 保留数据原本的位置返回数组
"""
c = np.array([[[1,2,3],[4,5,6],[7,8,9],[1,2,3]]])
print(c)
print('形状',c.shape) # 形状
print(c.max(),c.min()) # 最大值，最小值
# 切片
# 三维数组的shape[0]代表图片上的第几行,shape[1]代表图片上的第几列, shape[2] 代表有几个通道 
print(c[:][:][0])
print(c[:][0][1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [1 2 3]]]
形状 (1, 4, 3)
9 1
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
[4 5 6]


In [5]:
"""
 创建数组 arange() 默认：一维数组
 更多维度 reshape（）：传入一个数组（，，，）可以定制多维度的形状
"""
ran = np.arange(20)  # 和range（）方法对比
print(ran)
ran1 = np.arange(12)
print(ran1)
ran2 = np.arange(12).reshape((2,6))
print(ran2)
ran3 = np.arange(12).reshape((1,3,4))
print(ran3)
[[[1,2,3,4],[2,3,4,5]]]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


[[[1, 2, 3, 4], [2, 3, 4, 5]]]

In [6]:
"""
参数 元组 shape
创建数组0填充形状的多维数组 zeros（）
    默认类型：float
    dtype 可以设置元素类型 np.unit8代表整数
    astype 重置数组元素类型
创建数组1填充形状的多维数组 ones（）

"""
z = np.zeros((3,3),dtype=np.uint8)  # 全部为0，类型是整型
print(z)
f = z.astype(np.float64)  # 类型是浮点
print(f)
one = np.ones((3,3),detype=np.uint8) # 全部为1，类型是整型
print(one)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


TypeError: ones() got an unexpected keyword argument 'detype'

In [7]:
import os
print((os.path.abspath('.')))

E:\大二上学期内容\hmd\Numpy


In [8]:
"""
repeat():重复元素  1.元素 
                   2.重复次数
"""
f = np.repeat((3,4,5),4)
print(f)

[3 3 3 3 4 4 4 4 5 5 5 5]


In [9]:
"""
广播（Broadcasting）
     广播是一种强大的机制，它允许numpy在执行算术运算时使用不同形状的数组
     s.shape = b.shape 形状相同
"""
# 形状相同
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a*b
print(c)   # 运行结果为  对应位置相乘[ 10  40  90 160]

# 形状不同的
num1 = np.array([[1,2,3],[10,10,10],[20,20,20],[30,30,30]])
num2 = np.array([1,2,3])
num3 = num1+num2
print(num3)  #运行结果为： num1中的都与num2中相加
print("**************************")
# 二维加三维
n1 = np.array([[1,2,3],[4,5,6]])
n2 = np.array([[[1,2,3],[4,5,6]]])
n3 = n1+n2
print(n3)

[ 10  40  90 160]
[[ 2  4  6]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
**************************
[[[ 2  4  6]
  [ 8 10 12]]]


In [10]:
"""
统计函数： 从数组中快速查询最小，最大，百分位标准差，方差等
amin()参数：axis 1行，0列
amax()
ptp() 最大值-最小值的差
percentile（） 度量，百分比 1.数组 2.半分比 0-100 3.axis
median() 计算数组的（中位数）中值
mean（） 算数平均值
std() 标准差 sqrt(mean(x-x.mean())**2)
      标准差是一组数组的平均值分散成都的一种变量
var（） 方差 mean（（x-x.mean()**2））
         平均数之差的平方的平均数
加权平均数 ：average（）各个数值乘以相应的权数，然后总求和得到总体值，再除以总数
参数：weights：权重系数（可选参数，默认为一）

"""
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print(a)
print('行最大值',np.amax(a,axis=1))
print('列最大值',np.amax(a,axis=0))
print('默认最大值',np.amax(a))
print('行最小值',np.amin(a,axis=1))
print('行最小值',np.amin(a,axis=0))
print("*************************************")
# 百分值 50%的分位数，a排序后的中位数
print('百分值',np.percentile(a,50))
print('百分值',np.percentile(a,50))
print('百分值',np.percentile(a,50,axis=0))
print('百分值 维持数组形状保持不变',np.percentile(a,50,axis=0,keepidms=True))




[[3 7 5]
 [8 4 3]
 [2 4 9]]
行最大值 [7 8 9]
列最大值 [8 7 9]
默认最大值 9
行最小值 [3 3 2]
行最小值 [2 4 3]
*************************************
百分值 4.0
百分值 4.0
百分值 [3. 4. 5.]


TypeError: percentile() got an unexpected keyword argument 'keepidms'

In [11]:
# 中位数
print('中位数',np.median(a))
print('行中位数',np.median(a,axis=1))
print('列中位数',np.median(a,axis=0))

中位数 4.0
行中位数 [5. 4. 4.]
列中位数 [3. 4. 5.]
