In [1]:
import numpy as np

In [2]:
"""
   rand
   
"""

# 创建一个4行2列的随机数据
a = np.random.rand(4,2)  #可以取到0取不到1
print('4行2列',a)

# 3行3列的
b = np.random.rand(3,3)
print('3行3列',b)

4行2列 [[0.07115257 0.63574843]
 [0.59313578 0.52854083]
 [0.95309549 0.75365045]
 [0.73051745 0.63596014]]
3行3列 [[0.45254254 0.13624164 0.47934687]
 [0.11557834 0.67398634 0.08062677]
 [0.86821078 0.23176029 0.92155547]]


In [3]:
"""
   numpy.random.randon()
"""

from matplotlib import  pyplot as plt
# a = np.random.randint(low,high=50,size=100,dtype='1')
a = np.random.randint(10)
print(a)    # 一维  以0为均值以1为标准差

# 绘制直方图
plt.hist(a)

6


(array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]),
 array([5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5]),
 <a list of 10 Patch objects>)

In [4]:
"""
   numpy.random.randint()
   返回随机整数，范围区间为[low，high]，包含low，不包含high
   参数：low为最小值，high为最大值，size维数组维度大小，dtype为数据类型，默认的数据类型是np.int
   high没有填写时，默认生成随机数的范围是[1，low)

"""
# 指定最小值，没有最大值（0--最小值）
a = np.random.randint(10,size=5)
print('一维',a)
# 指定最大值和最小值
b = np.random.randint(2,10,size=5)
print('一维',b)
# 生成二维
c = np.random.randint(2,10,size=(2,5))  # 二维
print('二维',c)
#生成三维
d = np.random.randint(2,10,size=(2,2,5))
print('三维',d)
# 负数
num= np.random.randint(-1,5,size=(2,2))
print('负数',num)

一维 [9 0 6 7 7]
一维 [6 8 8 6 2]
二维 [[5 2 3 7 3]
 [9 4 7 7 8]]
三维 [[[3 5 8 7 3]
  [5 2 9 6 5]]

 [[3 2 9 7 6]
  [6 5 6 3 9]]]
负数 [[-1  2]
 [ 2  2]]


In [5]:
"""
返回半开区间的随机浮点数[0.0,1.0]
numpy.random.samply(size=None)
"""


# 生成2行3列
a = np.random.sample((2,3))
print(a)

# 生成2块   2行3列 ---------三维
b = np.random.sample()

[[0.04335586 0.51320409 0.14731393]
 [0.37425213 0.8066883  0.28766819]]


In [6]:
"""
   随机种子：numpy.random.seed()  
   seed（）值每一次生成都要一样，不一样没有效果

"""
np.random.seed(2)
a = np.random.randn(3,3)
np.random.seed(2)
b = np.random.randn(3,3)
print('a',b)
print('b',b)

a [[-0.41675785 -0.05626683 -2.1361961 ]
 [ 1.64027081 -1.79343559 -0.84174737]
 [ 0.50288142 -1.24528809 -1.05795222]]
b [[-0.41675785 -0.05626683 -2.1361961 ]
 [ 1.64027081 -1.79343559 -0.84174737]
 [ 0.50288142 -1.24528809 -1.05795222]]


In [7]:
"""
正态分布： numpy.random.normal()
numpy.random.normal(loc=0.0，scale=1.0，size=None)
作用：
    返回一个由size指定形状的数组，数组中的值服从μ=loc，标准差σ=scale的正态分布
参数：
    loc：float型或者float型的类数组对象
    scale：指定标准差σ
    size：int型或int型的元组，指定数组的形状。如果不提供size，且loc和scale为标量
         （不是类数组对象），则服从一个该分布的随机函数
"""
# 均值为0，标准差为1
a = np.random.normal(0,1,(3,2))
print(a)
# 自定义均值和标准差
# 均值为1，标准差为3
b = np.random.normal(1,3,(3,2))
# 符合正态分布的情况
print(b)


[[-0.90900761  0.55145404]
 [ 2.29220801  0.04153939]
 [-1.11792545  0.53905832]]
[[-0.7884791   0.94260851]
 [ 4.52500366 -1.24361285]
 [ 1.02707575 -1.63432368]]


In [8]:
"""
数组的其他函数：numpy.resize()返回指定形状的新数组
           1.numpy.resize(arr,shape)：有返回值，返回复制内容；如果维度不够，会使用原数组数据补齐
           2.ndarray.resize(shape,refcheck=False):修改原数组，不会返回数据；如果维度不够，会使用0补齐
"""
h = np.array([[1,2,3],[4,5,6]])
print(h)
#  numpy.resize(arr,shape)
a =  np.resize(h,(3,3))
print(a)
# ndarray.resize(shape,refcheck=False)
a.resize((3,3),refcheck=False)
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]]
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [9]:
"""
numpy.append(arr，values，axis=None) 在数组末尾添加值，返回一个一维数组
参数：
     arr：输入的数组
     values：向arr数组中添加的值，需要和arr数组的形状一致
     axis：默认为None，返回的是一维数组；
           当axis = 0 时，追加的值会添加到行，列保持不变
           axis=1时，则恰好相反
"""

h = np.array([[1,2,3],[4,5,6]])  # 二维
print(h)
print('添加元素：',np.append(h,[7,8,9]))
# 指定 axis=0 行
print('添加元素 行')
print(np.append(h,[[7,8,9]],axis=0)) #与h保持一致是二维
# 指定axis=1 列
print('添加元素 列') # 在指定列时要加上行
print(np.append(h,[[5,5,5],[7,8,9]],axis=1))#[[5,5,5]行,[7,8,9]列]

[[1 2 3]
 [4 5 6]]
添加元素： [1 2 3 4 5 6 7 8 9]
添加元素 行
[[1 2 3]
 [4 5 6]
 [7 8 9]]
添加元素 列
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [10]:
"""
numpy.insert(arr,obj,value,axis)
参数：
    arr：要输入的数组
    obj：索引值，在索引值之前插入values值
    values：要插入的值
    axis：指定的轴，如果没有则输入数组会展开为一维数组
"""

a = np.array([[1,2],[3,4],[5,6]])  #原数组
print(a)
# 不指定
print(np.insert(a,3,[11,12]))  # 在3和4之间切开了
# 指定axis=0 行 
print('指定行',np.insert(a,1,11,axis=0))
# 指定axis=1
print('指定列',np.insert(a,1,11,axis=1))

[[1 2]
 [3 4]
 [5 6]]
[ 1  2  3 11 12  4  5  6]
指定行 [[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
指定列 [[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]
